### ISSUE TITLE
Add Trailing Slash Handler (for routes)

### ISSUE THREAD

**Issue by gartmand** [excellaco/play-slick-postgres.g8#11]

**Comment by gartmand** [comment]
@vickumar1981 If you provide me with the code I can incorporate it, or you can do a PR.

**Comment by vickumar1981** [comment]
https://gist.github.com/vickumar1981/5c0b51ab38f867b85483b166f673676c

i usually put it under `/app/handlers`.

and then in `application.conf`:

```
play {
  http.requestHandler = "handlers.TrailingSlashRequestHandler"
  ...
}
```
